/**
 * build-css.mjs — assemble the shipped bunnyquery.css.
 *
 * bunnyquery.css = src/widget.css (widget chrome + design tokens + chat
 * container/layout) + styles/chat.css (the shared chat surface — bubbles,
 * markdown, links, queue/cancel — which is also exported as
 * `bunnyquery/styles/chat.css` and consumed by the agent.vue admin chatbox).
 * Edit those two sources, never bunnyquery.css.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const here = (p) => fileURLToPath(new URL(p, import.meta.url));

const widget = readFileSync(here('../src/widget.css'), 'utf8');
const chat = readFileSync(here('../styles/chat.css'), 'utf8');

const header =
  '/* GENERATED by scripts/build-css.mjs — DO NOT EDIT.\n' +
  ' * = src/widget.css (widget chrome + tokens + chat container)\n' +
  ' * + styles/chat.css (shared chat surface, also bunnyquery/styles/chat.css).\n' +
  ' * Edit those sources, then run `npm run build`. */\n\n';

writeFileSync(here('../bunnyquery.css'), header + widget.trimEnd() + '\n\n' + chat);
console.log('[build-css] bunnyquery.css = src/widget.css + styles/chat.css');
